/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-09-02 02:19:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write(" <style>  \r\n");
      out.write("      section {\r\n");
      out.write("        /* border: 2px solid;    */\r\n");
      out.write("        height: 500px;\r\n");
      out.write("        width: 600px;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        margin-left:25%;\r\n");
      out.write("        margin-top: auto;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      form {\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        border: 2px solid;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        margin-top: 40px;\r\n");
      out.write("        margin-left: 30px;\r\n");
      out.write("        padding-top: 40px;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("        width: 250px;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        background: linear-gradient(90deg, rgba(238,174,202,1) 0%, rgba(148,187,233,1) 100%);\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      img {\r\n");
      out.write("        height: 400px;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("      }\r\n");
      out.write("      #btn {\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        margin-left: 60px;\r\n");
      out.write("        height: 25px;\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        background-color: rgb(225, 225, 234);\r\n");
      out.write("      }\r\n");
      out.write("      .login-logo{\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        padding-left: 70px;\r\n");
      out.write("      }\r\n");
      out.write("      .input-area{\r\n");
      out.write("        padding-top: 40px;\r\n");
      out.write("      }\r\n");
      out.write("      input{\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        border: none;\r\n");
      out.write("      }\r\n");
      out.write("      input:hover{\r\n");
      out.write("        border: 2px solid;\r\n");
      out.write("      }\r\n");
      out.write("      #btn:hover{\r\n");
      out.write("        transform: scale(1.1);\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<section>\r\n");
      out.write("      <img\r\n");
      out.write("        alt=\"\"src=\"https://img.freepik.com/free-vector/login-concept-illustration_114360-757.jpg?size=626&ext=jpg&ga=GA1.1.1557645315.1724575942&semt=ais_hybrid\"/>\r\n");
      out.write("      <form action=\"login\">\r\n");
      out.write("        <div><img src=\"https://cdn-icons-png.flaticon.com/128/9386/9386837.png\"class=\"login-logo\"></div>\r\n");
      out.write("        <div class=\"input-area\">\r\n");
      out.write("        <svg\r\n");
      out.write("          xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("          width=\"20\"\r\n");
      out.write("          height=\"20\"\r\n");
      out.write("          fill=\"currentColor\"\r\n");
      out.write("          class=\"bi bi-person-bounding-box\"\r\n");
      out.write("          viewBox=\"0 0 16 16\"\r\n");
      out.write("        >\r\n");
      out.write("          <path\r\n");
      out.write("            d=\"M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 \r\n");
      out.write("                   1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5M.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0\r\n");
      out.write("                   0 1 0 14.5v-3a.5.5 0 0 1 .5-.5m15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5\"\r\n");
      out.write("          />\r\n");
      out.write("          <path\r\n");
      out.write("            d=\"M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0\"\r\n");
      out.write("          />\r\n");
      out.write("        </svg>\r\n");
      out.write("         <input type=\"email\" name=\"email\" /> <br /><br />\r\n");
      out.write("        <svg\r\n");
      out.write("          xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("          width=\"20\"\r\n");
      out.write("          height=\"20\"\r\n");
      out.write("          fill=\"currentColor\"\r\n");
      out.write("          class=\"bi bi-file-lock\"\r\n");
      out.write("          viewBox=\"0 0 16 16\"\r\n");
      out.write("        >\r\n");
      out.write("          <path\r\n");
      out.write("            d=\"M8 5a1 1 0 0 1 1 1v1H7V6a1 1 0 0 1 1-1m2 2.076V6a2 2 0 1 0-4 0v1.076c-.54.166-1 .597-1 1.224v2.4c0 .816.781 1.3 1.5 1.3h3c.719 0 1.5-.484 1.5-1.3V8.3c0-.627-.46-1.058-1-1.224M6.105 8.125A.64.64 0 0 1 6.5 8h3a.64.64 0 0 1 .395.125c.085.068.105.133.105.175v2.4c0 .042-.02.107-.105.175A.64.64 0 0 1 9.5 11h-3a.64.64 0 0 1-.395-.125C6.02 10.807 6 10.742 6 10.7V8.3c0-.042.02-.107.105-.175\"\r\n");
      out.write("          />\r\n");
      out.write("          <path\r\n");
      out.write("            d=\"M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1\"\r\n");
      out.write("          />\r\n");
      out.write("        </svg>\r\n");
      out.write("         <input type=\"telephone\" name=\"phone\" /><br /><br />\r\n");
      out.write("        <input id=\"btn\" type=\"submit\" value=\"Login\" />\r\n");
      out.write("    </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
